### ISSUE TITLE
Issues with test suite

### ISSUE THREAD

**Issue by bbuing9** [alisawuffles/wanli#1]
Hi, Alisa. Thanks for the exciting work and your effort to make it publicly available!

Now, I'm trying to benchmark your NLP test suite (Table 3) to measure the performance of my own model.

However, I found that there are some questions and issues as follow:

1. After training with MNLI data, we have 3-way classifier. However, some datasets have two classes (entailment vs non-entailment). How do you treat this difference? "Non-entailment" is corresponding to "contradiction" or both "contradiction and neutral"?

2. In case of fever-nli, it is not released from your google drive and the golden label of dev set is also not available from the referred link [1]. I'm trying to use the other's one , but it shows a significantly lower performance.. (with MNLI trained model, your report: 68.29, this dataset: 42~43) Can you release this fever-nli similar to other datasets? or how can I get the golden label of dev set in here? 

[1] https://github.com/easonnie/combine-FEVER-NSMN/blob/master/other_resources/nli_fever.md
[2] https://huggingface.co/datasets/pietrolesci/nli_fever/viewer/pietrolesci--nli_fever/dev

Thank you so much!

**Comment by alisawuffles** [comment]
Hello! Thank you for the questions.

1. For binary test sets, if the model predicts either contradiction OR neutral, we count it as a non-entailment prediction (since neutral and contradictory hypotheses are both not-entailed by the premise).
2. Oops! It looks like I forgot to upload FEVER-NLI to the Google drive folder. I just [uploaded it](https://drive.google.com/drive/u/0/folders/1l0GSxNmleUl_OCukiuVvQypS3vST1a4r)! For reference, you can also see how I preprocessed the FEVER NLI dataset [here](https://github.com/alisawuffles/wanli/blob/main/data_preprocessing/preprocess_fevernli.py).
